#!/usr/bin/env bash
#Script that displays listening ports that only shows listening sockets
#and that shows the PID and name of the program to which each socket belongs

netstat -lp

# -t (TCP)
# -u (UDP)
# -x (UNIX)
# -l (Listen)
# -p (Programm/PID)
