#!/usr/bin/env bash
# Configures localhost and facebook.com IP resolution

# Remove existing mapping entries
sudo sed -i '/localhost/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

# Add new mappings
sudo echo "127.0.0.2 localhost" >> /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts
